# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\add.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.Dialog=Dialog
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.setModal(True)
        Dialog.resize(430, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setToolTipDuration(2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        Dialog.setFont(font)

        # 窗口居中
        self.screen = QtWidgets.QDesktopWidget().screenGeometry()
        size = Dialog.frameGeometry()
        Dialog.move((self.screen.width() - size.width()) / 2, 0)

        # 背景白色
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)

        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 191, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.s_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.s_label.setMinimumSize(QtCore.QSize(0, 30))
        self.s_label.setObjectName("s_label")
        self.horizontalLayout_15.addWidget(self.s_label)
        self.s_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.s_input.setMinimumSize(QtCore.QSize(50, 30))
        self.s_input.setObjectName("s_input")
        self.horizontalLayout_15.addWidget(self.s_input)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 10, 191, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.adj_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.adj_label.setMinimumSize(QtCore.QSize(0, 30))
        self.adj_label.setObjectName("adj_label")
        self.horizontalLayout_11.addWidget(self.adj_label)
        self.adj_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.adj_input.setMinimumSize(QtCore.QSize(50, 30))
        self.adj_input.setObjectName("adj_input")
        self.horizontalLayout_11.addWidget(self.adj_input)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 191, 32))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.dis_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.dis_label.setMinimumSize(QtCore.QSize(80, 30))
        self.dis_label.setObjectName("dis_label")
        self.horizontalLayout_13.addWidget(self.dis_label)
        self.dis_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.dis_input.setMinimumSize(QtCore.QSize(50, 30))
        self.dis_input.setObjectName("dis_input")
        self.horizontalLayout_13.addWidget(self.dis_input)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(220, 60, 191, 32))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.line_label.setMinimumSize(QtCore.QSize(80, 30))
        self.line_label.setObjectName("line_label")
        self.horizontalLayout_8.addWidget(self.line_label)
        self.line_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.line_input.setMinimumSize(QtCore.QSize(50, 30))
        self.line_input.setObjectName("line_input")
        self.horizontalLayout_8.addWidget(self.line_input)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 110, 191, 32))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.x_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.x_label.setMinimumSize(QtCore.QSize(80, 30))
        self.x_label.setObjectName("x_label")
        self.horizontalLayout_16.addWidget(self.x_label)
        self.x_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.x_input.setMinimumSize(QtCore.QSize(50, 30))
        self.x_input.setObjectName("x_input")
        self.horizontalLayout_16.addWidget(self.x_input)

        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(220, 110, 191, 32))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.y_label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.y_label.setMinimumSize(QtCore.QSize(80, 30))
        self.y_label.setObjectName("y_label")
        self.horizontalLayout_14.addWidget(self.y_label)
        self.y_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.y_input.setMinimumSize(QtCore.QSize(50, 30))
        self.y_input.setObjectName("y_input")
        self.horizontalLayout_14.addWidget(self.y_input)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(80, 160, 271, 32))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelx_label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.labelx_label.setMinimumSize(QtCore.QSize(80, 30))
        self.labelx_label.setObjectName("labelx_label")
        self.horizontalLayout_12.addWidget(self.labelx_label)
        self.labelx_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.labelx_input.setMinimumSize(QtCore.QSize(50, 30))
        self.labelx_input.setObjectName("labelx_input")
        self.horizontalLayout_12.addWidget(self.labelx_input)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(80, 210, 271, 32))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labely_label = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.labely_label.setMinimumSize(QtCore.QSize(80, 30))
        self.labely_label.setObjectName("labely_label")
        self.horizontalLayout_10.addWidget(self.labely_label)
        self.labely_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.labely_input.setMinimumSize(QtCore.QSize(50, 30))
        self.labely_input.setObjectName("labely_input")
        self.horizontalLayout_10.addWidget(self.labely_input)
        #ok按钮
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(100, 270, 80, 40))
        self.ok.setObjectName("ok")
        #cancel按钮
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(250, 270, 80, 40))
        self.cancel.setObjectName("cancel")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加站点"))
        self.line_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">线  路：</span></p></body></html>"))
        self.labely_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">标签Y坐标：</span></p></body></html>"))
        self.adj_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">相邻站：</span></p></body></html>"))
        self.ok.setText(_translate("Dialog", "确认"))
        self.labelx_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">标签X坐标：</span></p></body></html>"))
        self.dis_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">距  离：</span></p></body></html>"))
        self.y_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Y坐标：</span></p></body></html>"))
        self.s_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">添加站：</span></p></body></html>"))
        self.x_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">X坐标：</span></p></body></html>"))
        self.cancel.setText(_translate("Dialog", "取消"))

